CREATE USER C##PROJECT IDENTIFIED BY PROJECT;

GRANT RESOURCE, CONNECT TO C##PROJECT;

ALTER USER C##PROJECT DEFAULT TABLESPACE USERS QUOTA UNLIMITED ON USERS;


----- 과제 영역
-- 사용자 계정 정의
CREATE USER C##PROJECT IDENTIFIED BY PROJECT;

GRANT RESOURCE, CONNECT TO C##PROJECT;

ALTER USER C##PROJECT DEFAULT TABLESPACE USERS QUOTA UNLIMITED ON USERS;
------------------------------------------------------------------------------
DROP TABLE USERS;
DROP TABLE PLAN;
------------------------------------------------------------------------------
-- DDL FOR TABLE USERS

CREATE TABLE USERS (
    USER_ID VARCHAR2(15) CONSTRAINT PK_USERID PRIMARY KEY,
    USER_PW VARCHAR2(25) CONSTRAINT NN_USERPW NOT NULL,
    CONSTRAINT CK_USERPW CHECK(
        USER_PW LIKE '%@%' OR USER_PW LIKE '%!%' OR USER_PW LIKE '%?%')
);

-- COMMENTS FOR COLUMNS IN TABLE USERS
COMMENT ON COLUMN USERS.USER_ID IS '아이디';
COMMENT ON COLUMN USERS.USER_PW IS '비밀번호';

-- DATA OF TABLE USERS
INSERT INTO C##PROJECT.USERS (USER_ID, USER_PW)
    VALUES ('leah', 'w23@');
INSERT INTO C##PROJECT.USERS (USER_ID, USER_PW)
    VALUES ('elliott', 'a5!');
INSERT INTO C##PROJECT.USERS (USER_ID, USER_PW)
    VALUES ('abigail', 'a13?');
INSERT INTO C##PROJECT.USERS (USER_ID, USER_PW)
    VALUES ('sebastian', 'w10@');

DELETE FROM USERS;
-------------------------------------------------------------------------------
-- DDL FOR TABLE PLAN
CREATE TABLE PLAN (
    PLAN_ID NUMBER CONSTRAINT PK_PLANID PRIMARY KEY,
    PLAN_TYPE NUMBER CONSTRAINT NN_PLANTYPE NOT NULL,   -- 1: Plan, 2: Period, 3: OneDay
    PLAN_TITLE VARCHAR2(100) NOT NULL,
    PLAN_DATE DATE NOT NULL,
    PLAN_DUE DATE,
    PLAN_TIME VARCHAR2(5),
    USER_ID VARCHAR2(15),
    CONSTRAINT FK_USERID FOREIGN KEY(USER_ID) REFERENCES USERS(USER_ID)
);
-- COMMENTS FOR COLUMNS IN TABLE PLAN
COMMENT ON COLUMN PLAN.PLAN_ID IS '저장번호';
COMMENT ON COLUMN PLAN.PLAN_ID IS '일정분류';
COMMENT ON COLUMN PLAN.PLAN_TITLE IS '제목';
COMMENT ON COLUMN PLAN.PLAN_DATE IS '날짜';
COMMENT ON COLUMN PLAN.PLAN_DUE IS '마감일';
COMMENT ON COLUMN PLAN.PLAN_TIME IS '시간';
COMMENT ON COLUMN PLAN.USER_ID IS '사용자';

-- DATA OF TABLE PLAN
INSERT INTO C##PROJECT.PLAN (PLAN_ID, PLAN_TYPE, PLAN_TITLE, PLAN_DATE, PLAN_DUE, PLAN_TIME, USER_ID)
    VALUES (1, 3, 'egghunt', '2026/03/13', NULL, '09:00', 'abigail');
INSERT INTO C##PROJECT.PLAN (PLAN_ID, PLAN_TYPE, PLAN_TITLE, PLAN_DATE, PLAN_DUE, PLAN_TIME, USER_ID)
    VALUES (2, 3,  'flower ball', '2026/03/24', NULL, '10:00', 'elliott');
INSERT INTO C##PROJECT.PLAN (PLAN_ID, PLAN_TYPE, PLAN_TITLE, PLAN_DATE, PLAN_DUE, PLAN_TIME, USER_ID)
    VALUES (3, 3, 'potluck', '2026/06/11', NULL, '11:00', 'sebastian');
INSERT INTO C##PROJECT.PLAN (PLAN_ID, PLAN_TYPE, PLAN_TITLE, PLAN_DATE, PLAN_DUE, PLAN_TIME, USER_ID)
    VALUES (4, 2, 'fishing contest', '2026/06/20', '2026/06/21', NULL, 'elliott');
INSERT INTO C##PROJECT.PLAN (PLAN_ID, PLAN_TYPE, PLAN_TITLE, PLAN_DATE, PLAN_DUE, PLAN_TIME, USER_ID)
    VALUES (5, 3, 'stardew fair', '2026/09/16', NULL, '14:00', 'leah');
INSERT INTO C##PROJECT.PLAN (PLAN_ID, PLAN_TYPE, PLAN_TITLE, PLAN_DATE, PLAN_DUE, PLAN_TIME, USER_ID)
    VALUES (6, 3, 'halloween', '2026/09/27', NULL, '22:00', 'abigail');
INSERT INTO C##PROJECT.PLAN (PLAN_ID, PLAN_TYPE, PLAN_TITLE, PLAN_DATE, PLAN_DUE, PLAN_TIME, USER_ID)
    VALUES (7, 3, 'ice festa', '2026/12/08', NULL, '12:00', 'leah');
INSERT INTO C##PROJECT.PLAN (PLAN_ID, PLAN_TYPE, PLAN_TITLE, PLAN_DATE, PLAN_DUE, PLAN_TIME, USER_ID)
    VALUES (8, 2, 'night market', '2026/12/15', '2026/12/16', NULL, 'sebastian');
-------------------------------------------------------------------------------

COMMIT;

