-- JDBC 계정 생성
CREATE USER C##JDBC IDENTIFIED BY JDBC;

-- 권한 부여: CONNECT, RESOURCE
GRANT CONNECT, RESOURCE TO C##JDBC;

-- 테이블 스페이스 부여
ALTER USER C##JDBC DEFAULT TABLESPACE USERS QUOTA UNLIMITED ON USERS;

