-- * KH_연습 문제 *
-- * 연습용 계정 생성 후 아래 문제를 풀어봅시다 *
-- * 계정 정보 : C##TEST / TEST *
-- * 테이블이 존재하지 않을 경우, [연습 문제 6]을 참고하여 생성해 주세요. *
-- 1. TB_DEPT 테이블에 아래 3개의 부서 데이터를 삽입하는 SQL을 작성하세요.
--    10번: '인사팀'
--    20번: '개발팀'
--    30번: '디자인팀'
INSERT INTO TB_DEPT (DEPT_CD, DEPT_NAME)
            VALUES (10, '인사팀');
INSERT INTO TB_DEPT (DEPT_CD, DEPT_NAME)
            VALUES (20, '개발팀');
INSERT INTO TB_DEPT (DEPT_CD, DEPT_NAME)
            VALUES (30, '디자인팀');

SELECT * FROM TB_DEPT;

-- 2. TB_EMP 테이블에 아래의 사원 정보를 삽입하는 SQL을 작성하세요.
--    사원번호: 1001, 이름: '홍길동', 성별: (기본값 설정 적용), 부서코드: 10, 연락처: '010-1111-2222'
--    사원번호: 1002, 이름: '김철수', 성별: 'M', 부서코드: 20, 연락처: '010-3333-4444'
--    사원번호: 1003, 이름: '이영희', 성별: 'F', 부서코드: 20, 연락처: '010-5555-6666'
DROP TABLE TB_EMP;
CREATE TABLE TB_EMP (
    EMP_NO NUMBER /* CONSTRAINT PK_TD*/ PRIMARY KEY,
    EMP_NAME VARCHAR(20) /*CONSTRAINT NN_TD*/ NOT NULL,
    GENDER CHAR(1) DEFAULT 'M' CONSTRAINT CK_TE CHECK(GENDER IN ('M', 'F')),
    DEPT_CD NUMBER /*REFERENCES TB_DEPT(DEPT_CD)*/,
    CONTACT VARCHAR2(15) CONSTRAINT UQ_TE UNIQUE,
    
    CONSTRAINT FK_TE FOREIGN KEY(DEPT_CD) REFERENCES TB_DEPT(DEPT_CD)
);


INSERT INTO TB_EMP (EMP_NO, EMP_NAME, DEPT_CD, CONTACT)
            VALUES (1001, '홍길동', 10, '010-1111-2222');
INSERT INTO TB_EMP (EMP_NO, EMP_NAME, GENDER, DEPT_CD, CONTACT)
            VALUES (1002, '김철수', 'M', 20, '010-3333-4444');
INSERT INTO TB_EMP (EMP_NO, EMP_NAME, GENDER, DEPT_CD, CONTACT)
            VALUES (1003, '이영희', 'F', 20, '010-5555-6666');

-- 3. 아래의 SQL을 실행했을 때 에러가 발생하는 원인을 제약조건과 연결 지어 설명하고, 정상적으로 삽입되도록
--    SQL을 수정하세요.
--    INSERT INTO TB_EMP (EMP_NO, EMP_NAME, GENDER, DEPT_CD, CONTACT)
--    VALUES (1004, '박민수', 'X', 40, '010-1111-2222');
/*
    에러 발생 원인
    1) GENDER는 CHECK(GENDER IN('M', 'F') 제약조건이 있으므로 M, F 외의 다른 글자를 입력할 수 없다.
    2) DEPT_CD는 TB_DEPT라는 부모 테이블에서 DEPT_CD를 참조하는 FOREIGN KEY 제약조건이 있으므로
       TB_DEPT 테이블에 존재하지 않는 DEPT_CD를 가질 수 없다.
    3) CONTACT는 UNIQUE 제약조건이 있으므로 다른 사람(홍길동)과 같은 값을 가질 수 없다.
*/
DELETE FROM TB_EMP WHERE EMP_NO = 1004;

INSERT INTO TB_EMP (EMP_NO, EMP_NAME, GENDER, DEPT_CD, CONTACT)
        VALUES (1004, '박민수', 'F', 30, '010-7777-8888');

SELECT * FROM TB_EMP;

-- 4. '개발팀'의 부서코드(DEPT_CD)가 20번에서 50번으로 변경되어야 합니다.
--    아래 작업 항목에 따라 SQL문을 작성하세요.
--    * TB_DEPT 테이블에서 개발팀의 부서코드를 50으로 변경하는 SQL을 작성하세요.
--    * 부서코드가 변경됨에 따라 TB_EMP 테이블에서 개발팀(기존 20번) 소속이었던 사원들의 부서코드
--      50으로 일괄 변경하는 SQL을 작성하세요.
UPDATE TB_EMP
SET DEPT_CD = NULL
WHERE DEPT_CD = 20;

UPDATE TB_DEPT
SET DEPT_CD = 50
WHERE DEPT_NAME = '개발팀';

UPDATE TB_EMP
SET DEPT_CD =50
WHERE DEPT_CD IS NULL;

-- 쌤 풀이!
-- * SIMPLE METHOD *
-- 1. ADD DATA INTO TABLE TB_DEPT (50, DEVELOPMENT DEPT)
INSERT INTO TB_DEPT VALUES (50, '개발팀');
-- 2. CHANGE EMPLOYEES' DEPT_CD WHOSE ORIGINAL DEPT_CD IS 20
UPDATE TB_EMP
SET DEPT_CD = 50
WHERE DEPT_CD = 20;
-- 3. DELETE DEPT_CD 20 FROM TB_DEPT TABLE
DELETE FROM TB_DEPT WHERE DEPT_CD = 20;

-- * COMPLICATED METHOD *
-- IF THERE IS A CONSTRAINT "UNIQUE(DEPT_NAME)" IN TB_DEPT TABLE...
-- WE COULDN'T USE THE SIMPLE METHOD THAT WE MENTIONED PRIORLY
ALTER TABLE TB_DEPT ADD CONSTRAINT UQ_TD UNIQUE(DEPT_NAME);

-- 1) COPY THE TABLE --> ONLY STRUCTURE & NOT NULL ARE COPIED
-- => WE CAN SKIP COPYING OTHER CONSTRAINTS
-- BACKUP DATA OF CORRESPONDING EMPLOYEE BY COPYING
CREATE TABLE TB_EMP_20
AS (SELECT * FROM TB_EMP WHERE DEPT_CD = 20);
SELECT * FROM TB_EMP_20;

-- 2) DELETE DATA OF EMPLOYEES WHOSE DEPT_CD IS 20
DELETE FROM TB_EMP WHERE DEPT_CD = 20;
SELECT * FROM TB_EMP;

-- 3) CHANGE DEPT_CD IN TB_DEPT TABLE
UPDATE TB_DEPT
SET DEPT_CD = 50
WHERE DEPT_CD = 20;
SELECT * FROM TB_DEPT;

-- 4) CHANGE DEPT_CD IN THE COPIED TABLE (TB_EMP_20)
UPDATE TB_EMP_20
SET DEPT_CD = 50;

SELECT * FROM TB_EMP_20;

-- 5) RESTORE EMPLOYEE DATA BY TB_EMP_20
INSERT INTO TB_EMP(EMP_NO, EMP_NAME, GENDER, DEPT_CD, CONTACT)
(SELECT * FROM TB_EMP_20);

SELECT * FROM TB_EMP;

-- 5. TB_DEPT 테이블에서 10번 부서('인사팀')를 삭제하려고 합니다.
-- 하지만 현재 10번 부서에는 '홍길동' 사원이 소속되어 있어 외래키 무결성 에러가 발생합니다.
-- 에러를 내지 않고 10번 부서를 안전하게 삭제하기 위한 SQL을 작성하세요.
UPDATE TB_EMP
SET DEPT_CD = NULL
WHERE DEPT_CD = 10;

DELETE FROM TB_DEPT
WHERE DEPT_CD = 10;

COMMIT;

-- TEACHER'S SOLUTION
-- 1) CASCADE (전체 삭제 >> 부모 테이블(TB_DEPT) / 자식 테이블(TB_EMP))
-- 2) NULL (부모 테이블에서만 삭제하고, 자식 테이블에서는 해당 값을 NULL로 변경)
--      => ON DELETE SET NULL
-- DELETE CONSTRAINT FOREIGN KEY AND RECREATE
ALTER TABLE TB_EMP DROP CONSTRAINT FK_TE;
ALTER TABLE TB_EMP ADD CONSTRAINT FK_TE FOREIGN KEY(DEPT_CD)
    REFERENCES TB_DEPT(DEPT_CD) ON DELETE SET NULL;
    
-- DELETE CORRESPONDING DEPARTMENT
DELETE FROM TB_DEPT WHERE DEPT_CD = 10;
SELECT * FROM TB_DEPT WHERE DEPT_CD = 10;

SELECT * FROM TB_DEPT;
SELECT * FROM TB_EMP;
COMMIT;