-- * KH 실습 문제 * --
-- 1. 인사관리부 부서의 사원들의 사번, 사원명, 보너스 조회
--- > 사원 (EMPLOYEE), 부서(DEPARTMENT)
-- * 오라클 구문 * --
SELECT EMP_ID, EMP_NAME, BONUS
FROM EMPLOYEE, DEPARTMENT
WHERE DEPT_CODE = DEPT_ID AND
    DEPT_TITLE = '인사관리부'
ORDER BY 1;

-- * ANSI 구문 * --
SELECT EMP_ID, EMP_NAME, BONUS
FROM EMPLOYEE
    JOIN DEPARTMENT ON DEPT_CODE = DEPT_ID
WHERE DEPT_TITLE = '인사관리부'
ORDER BY 1;

-- 2. 전체 부서의 부서코드, 부서명, 지역코드, 지역명 조회
-- * 부서(DEPARTMENT), 지역(LOCATION)
-- * 오라클 구문 * --
SELECT DEPT_ID, DEPT_TITLE, LOCAL_CODE, LOCAL_NAME
FROM DEPARTMENT, LOCATION
WHERE LOCATION_ID = LOCAL_CODE (+)
ORDER BY 1;

-- * ANSI 구문 * --
SELECT DEPT_ID, DEPT_TITLE, LOCAL_CODE, LOCAL_NAME
FROM DEPARTMENT
    LEFT JOIN LOCATION ON LOCATION_ID = LOCAL_CODE
ORDER BY 1;

-- 3. 보너스를 받는 사원의 사번, 사원명, 보너스, 부서명 조회
-- * 사원(EMPLOYEE), 부서(DEPARTMENT)
-- * 오라클 구문 * --
SELECT EMP_ID, EMP_NAME, BONUS, DEPT_TITLE
FROM EMPLOYEE, DEPARTMENT
WHERE BONUS IS NOT NULL AND
    DEPT_CODE = DEPT_ID
ORDER BY 1;

-- * ANSI 구문 * --
SELECT EMP_ID, EMP_NAME, BONUS, DEPT_TITLE
FROM EMPLOYEE
    JOIN DEPARTMENT ON DEPT_CODE = DEPT_ID
WHERE BONUS IS NOT NULL
ORDER BY 1;

-- 4. 총무부가 아닌 사원들의 사원명, 급여 조회
-- * 사원(EMPLOYEE), 부서(DEPARTMENT)
-- * 오라클 구문 * --
SELECT EMP_NAME, SALARY
FROM EMPLOYEE, DEPARTMENT
WHERE DEPT_CODE = DEPT_ID AND
    DEPT_TITLE != '총무부'
ORDER BY 1;

-- * ANSI 구문 * --
SELECT EMP_NAME, SALARY
FROM EMPLOYEE
    JOIN DEPARTMENT ON DEPT_CODE = DEPT_ID
WHERE DEPT_TITLE != '총무부'
ORDER BY 1;

-- 5. 사번, 사원명, 부서명, 지역명, 국가명 조회
--- * 사원(employee), 부서(DEPARTMENT), 지역(LOCATION), 국가(NATIONAL)
-- ** 오라클 구문 ** --
SELECT EMP_ID, EMP_NAME, DEPT_TITLE, LOCAL_NAME, NATIONAL_NAME
FROM EMPLOYEE, DEPARTMENT, LOCATION L, NATIONAL N
WHERE DEPT_CODE = DEPT_ID AND
    LOCATION_ID = LOCAL_CODE AND
    L.NATIONAL_CODE = N.NATIONAL_CODE
ORDER BY 1;

-- ** ANSI 구문 ** --
SELECT EMP_ID, EMP_NAME, DEPT_TITLE, LOCAL_NAME, NATIONAL_NAME
FROM EMPLOYEE
    JOIN DEPARTMENT ON DEPT_CODE = DEPT_ID
    JOIN LOCATION ON LOCATION_ID = LOCAL_CODE
    JOIN NATIONAL USING(NATIONAL_CODE)
ORDER BY 1;

-- 6. 사번, 사원명, 부서명, 직급명, 지역명, 국가명, 급여등급 조회
-- * 사원(EMPLOYEE), 부서(DEPARTMENT), 직급(JOB), 지역(LOCATION), 국가(NATIONAL), 급여등급(SAL_GRADE)
-- ** 오라클 구문 ** --
SELECT EMP_ID, EMP_NAME, DEPT_TITLE, JOB_NAME, LOCAL_NAME, NATIONAL_NAME, SAL_LEVEL
FROM EMPLOYEE E, DEPARTMENT, JOB J, LOCATION L, NATIONAL N, SAL_GRADE
WHERE E.JOB_CODE = J.JOB_CODE AND
    DEPT_CODE = DEPT_ID AND
    LOCATION_ID = LOCAL_CODE AND
    L.NATIONAL_CODE = N.NATIONAL_CODE AND
    SALARY BETWEEN MIN_SAL AND MAX_SAL
ORDER BY 1;

-- ** ANSI 구문 ** --
SELECT EMP_ID, EMP_NAME, DEPT_TITLE, JOB_NAME, LOCAL_NAME, NATIONAL_NAME, SAL_LEVEL
FROM JOB
    JOIN EMPLOYEE USING(JOB_CODE)
    JOIN DEPARTMENT ON DEPT_CODE = DEPT_ID
    JOIN LOCATION ON LOCATION_ID = LOCAL_CODE
    JOIN NATIONAL USING(NATIONAL_CODE)
    JOIN SAL_GRADE ON SALARY BETWEEN MIN_SAL AND MAX_SAL
ORDER BY 1;